// Migration: 002_load_greek_data
// Description: Load 100 verbs, 100 nouns, and articles

const articles = [
  // Definite articles
  { article: 'ο', is_definite: true, gender: 'masculine', number: 'singular', case: 'nominative' },
  { article: 'του', is_definite: true, gender: 'masculine', number: 'singular', case: 'genitive' },
  { article: 'τον', is_definite: true, gender: 'masculine', number: 'singular', case: 'accusative' },
  { article: 'τε', is_definite: true, gender: 'masculine', number: 'singular', case: 'vocative' },
  { article: 'η', is_definite: true, gender: 'feminine', number: 'singular', case: 'nominative' },
  { article: 'της', is_definite: true, gender: 'feminine', number: 'singular', case: 'genitive' },
  { article: 'την', is_definite: true, gender: 'feminine', number: 'singular', case: 'accusative' },
  { article: 'το', is_definite: true, gender: 'neuter', number: 'singular', case: 'nominative' },
  { article: 'του', is_definite: true, gender: 'neuter', number: 'singular', case: 'genitive' },
  { article: 'το', is_definite: true, gender: 'neuter', number: 'singular', case: 'accusative' },
  { article: 'οι', is_definite: true, gender: 'masculine', number: 'plural', case: 'nominative' },
  { article: 'των', is_definite: true, gender: 'masculine', number: 'plural', case: 'genitive' },
  { article: 'τους', is_definite: true, gender: 'masculine', number: 'plural', case: 'accusative' },
  { article: 'οι', is_definite: true, gender: 'feminine', number: 'plural', case: 'nominative' },
  { article: 'των', is_definite: true, gender: 'feminine', number: 'plural', case: 'genitive' },
  { article: 'τις', is_definite: true, gender: 'feminine', number: 'plural', case: 'accusative' },
  { article: 'τα', is_definite: true, gender: 'neuter', number: 'plural', case: 'nominative' },
  { article: 'των', is_definite: true, gender: 'neuter', number: 'plural', case: 'genitive' },
  { article: 'τα', is_definite: true, gender: 'neuter', number: 'plural', case: 'accusative' },
  // Indefinite articles
  { article: 'ένας', is_definite: false, gender: 'masculine', number: 'singular', case: 'nominative' },
  { article: 'ενός', is_definite: false, gender: 'masculine', number: 'singular', case: 'genitive' },
  { article: 'έναν', is_definite: false, gender: 'masculine', number: 'singular', case: 'accusative' },
  { article: 'μία', is_definite: false, gender: 'feminine', number: 'singular', case: 'nominative' },
  { article: 'μιας', is_definite: false, gender: 'feminine', number: 'singular', case: 'genitive' },
  { article: 'μία', is_definite: false, gender: 'feminine', number: 'singular', case: 'accusative' },
  { article: 'ένα', is_definite: false, gender: 'neuter', number: 'singular', case: 'nominative' },
  { article: 'ενός', is_definite: false, gender: 'neuter', number: 'singular', case: 'genitive' },
  { article: 'ένα', is_definite: false, gender: 'neuter', number: 'singular', case: 'accusative' },
];

const verbs = [
  { word: 'είμαι', english: 'to be', type: 'active' },
  { word: 'έχω', english: 'to have', type: 'active' },
  { word: 'κάνω', english: 'to do/make', type: 'active' },
  { word: 'πηγαίνω', english: 'to go', type: 'active' },
  { word: 'λέω', english: 'to say', type: 'active' },
  { word: 'δίνω', english: 'to give', type: 'active' },
  { word: 'βρίσκω', english: 'to find', type: 'active' },
  { word: 'ξέρω', english: 'to know', type: 'active' },
  { word: 'θέλω', english: 'to want', type: 'active' },
  { word: 'μπορώ', english: 'can', type: 'active' },
  { word: 'μένω', english: 'to stay/live', type: 'active' },
  { word: 'έρχομαι', english: 'to come', type: 'active' },
  { word: 'δουλεύω', english: 'to work', type: 'active' },
  { word: 'αγαπώ', english: 'to love', type: 'active' },
  { word: 'ακούω', english: 'to hear/listen', type: 'active' },
  { word: 'βλέπω', english: 'to see', type: 'active' },
  { word: 'αρχίζω', english: 'to begin', type: 'active' },
  { word: 'τελειώνω', english: 'to finish', type: 'active' },
  { word: 'ρωτώ', english: 'to ask', type: 'active' },
  { word: 'απαντώ', english: 'to answer', type: 'active' },
  { word: 'γράφω', english: 'to write', type: 'active' },
  { word: 'διαβάζω', english: 'to read', type: 'active' },
  { word: 'σκέφτομαι', english: 'to think', type: 'active' },
  { word: 'νιώθω', english: 'to feel', type: 'active' },
  { word: 'φοβάμαι', english: 'to fear', type: 'active' },
  { word: 'χαίρομαι', english: 'to be happy', type: 'active' },
  { word: 'λυπάμαι', english: 'to be sorry', type: 'active' },
  { word: 'πίνω', english: 'to drink', type: 'active' },
  { word: 'τρώω', english: 'to eat', type: 'active' },
  { word: 'κολυμπώ', english: 'to swim', type: 'active' },
  { word: 'τρέχω', english: 'to run', type: 'active' },
  { word: 'περπατώ', english: 'to walk', type: 'active' },
  { word: 'παίζω', english: 'to play', type: 'active' },
  { word: 'καθίζω', english: 'to sit', type: 'active' },
  { word: 'στέκομαι', english: 'to stand', type: 'active' },
  { word: 'κοιμάμαι', english: 'to sleep', type: 'active' },
  { word: 'ξυπνώ', english: 'to wake up', type: 'active' },
  { word: 'ντύνομαι', english: 'to dress', type: 'active' },
  { word: 'γυρίζω', english: 'to turn', type: 'active' },
  { word: 'σταματώ', english: 'to stop', type: 'active' },
  { word: 'συνεχίζω', english: 'to continue', type: 'active' },
  { word: 'χρησιμοποιώ', english: 'to use', type: 'active' },
  { word: 'αποκτώ', english: 'to obtain', type: 'active' },
  { word: 'χάνω', english: 'to lose', type: 'active' },
  { word: 'κερδίζω', english: 'to win', type: 'active' },
  { word: 'προσπαθώ', english: 'to try', type: 'active' },
  { word: 'εξηγώ', english: 'to explain', type: 'active' },
  { word: 'κατανοώ', english: 'to understand', type: 'active' },
  { word: 'ενδιαφέρομαι', english: 'to be interested', type: 'active' },
  { word: 'απολαμβάνω', english: 'to enjoy', type: 'active' },
  { word: 'υποφέρω', english: 'to suffer', type: 'active' },
  { word: 'αναγκάζω', english: 'to force', type: 'active' },
  { word: 'επιτρέπω', english: 'to allow', type: 'active' },
  { word: 'αποτυγχάνω', english: 'to fail', type: 'active' },
  { word: 'τολμώ', english: 'to dare', type: 'active' },
  { word: 'προτιμώ', english: 'to prefer', type: 'active' },
  { word: 'αποφεύγω', english: 'to avoid', type: 'active' },
  { word: 'εγκαταλείπω', english: 'to abandon', type: 'active' },
  { word: 'ξεχνώ', english: 'to forget', type: 'active' },
  { word: 'θυμάμαι', english: 'to remember', type: 'active' },
  { word: 'συμφωνώ', english: 'to agree', type: 'active' },
  { word: 'διαφωνώ', english: 'to disagree', type: 'active' },
  { word: 'ταιριάζω', english: 'to match', type: 'active' },
  { word: 'μοιάζω', english: 'to resemble', type: 'active' },
  { word: 'διαφέρω', english: 'to differ', type: 'active' },
  { word: 'αλλάζω', english: 'to change', type: 'active' },
  { word: 'μετατρέπω', english: 'to transform', type: 'active' },
  { word: 'κρατώ', english: 'to hold', type: 'active' },
  { word: 'αγκαλιάζω', english: 'to hug', type: 'active' },
  { word: 'χαιρετώ', english: 'to greet', type: 'active' },
  { word: 'φιλώ', english: 'to kiss', type: 'active' },
  { word: 'χτυπώ', english: 'to hit', type: 'active' },
  { word: 'σπρώχνω', english: 'to push', type: 'active' },
  { word: 'τραβώ', english: 'to pull', type: 'active' },
  { word: 'αποχωρώ', english: 'to withdraw', type: 'active' },
  { word: 'συγκεντρώνω', english: 'to concentrate', type: 'active' },
  { word: 'σημειώνω', english: 'to note', type: 'active' },
  { word: 'ονοματίζω', english: 'to name', type: 'active' },
  { word: 'κατηγορώ', english: 'to accuse', type: 'active' },
  { word: 'απολογούμαι', english: 'to apologize', type: 'active' },
  { word: 'επιμένω', english: 'to insist', type: 'active' },
  { word: 'υποχρεώνω', english: 'to oblige', type: 'active' },
  { word: 'δωρίζω', english: 'to donate', type: 'active' },
  { word: 'δανείζω', english: 'to lend', type: 'active' },
  { word: 'δανείζομαι', english: 'to borrow', type: 'active' },
  { word: 'πληρώνω', english: 'to pay', type: 'active' },
  { word: 'κοστίζω', english: 'to cost', type: 'active' },
  { word: 'ζυγίζω', english: 'to weigh', type: 'active' },
  { word: 'μετράω', english: 'to measure', type: 'active' },
  { word: 'αναλύω', english: 'to analyze', type: 'active' },
  { word: 'συνδυάζω', english: 'to combine', type: 'active' },
];

const nouns = [
  { word: 'άνθρωπος', english: 'person/human', gender: 'masculine', declension: 1 },
  { word: 'γυναίκα', english: 'woman', gender: 'feminine', declension: 1 },
  { word: 'άντρας', english: 'man', gender: 'masculine', declension: 1 },
  { word: 'παιδί', english: 'child', gender: 'neuter', declension: 3 },
  { word: 'κορίτσι', english: 'girl', gender: 'neuter', declension: 3 },
  { word: 'αγόρι', english: 'boy', gender: 'neuter', declension: 3 },
  { word: 'μάνα', english: 'mother', gender: 'feminine', declension: 1 },
  { word: 'πατέρας', english: 'father', gender: 'masculine', declension: 1 },
  { word: 'αδελφός', english: 'brother', gender: 'masculine', declension: 2 },
  { word: 'αδελφή', english: 'sister', gender: 'feminine', declension: 1 },
  { word: 'γιος', english: 'son', gender: 'masculine', declension: 2 },
  { word: 'θυγατέρα', english: 'daughter', gender: 'feminine', declension: 1 },
  { word: 'εγγονός', english: 'grandson/grandchild', gender: 'masculine', declension: 2 },
  { word: 'εγγονή', english: 'granddaughter', gender: 'feminine', declension: 1 },
  { word: 'συζυγος', english: 'spouse', gender: 'masculine', declension: 2 },
  { word: 'φίλος', english: 'friend', gender: 'masculine', declension: 2 },
  { word: 'δάσκαλος', english: 'teacher', gender: 'masculine', declension: 2 },
  { word: 'μαθητής', english: 'student', gender: 'masculine', declension: 1 },
  { word: 'εργάτης', english: 'worker', gender: 'masculine', declension: 1 },
  { word: 'γιατρός', english: 'doctor', gender: 'masculine', declension: 2 },
  { word: 'νοσοκόμα', english: 'nurse', gender: 'feminine', declension: 1 },
  { word: 'δικηγόρος', english: 'lawyer', gender: 'masculine', declension: 2 },
  { word: 'δημοσιογράφος', english: 'journalist', gender: 'masculine', declension: 2 },
  { word: 'συγγραφέας', english: 'author', gender: 'masculine', declension: 1 },
  { word: 'μηχανικός', english: 'engineer', gender: 'masculine', declension: 2 },
  { word: 'αστυνόμος', english: 'police officer', gender: 'masculine', declension: 2 },
  { word: 'στρατιώτης', english: 'soldier', gender: 'masculine', declension: 1 },
  { word: 'πιλότος', english: 'pilot', gender: 'masculine', declension: 2 },
  { word: 'κυβερνήτης', english: 'captain', gender: 'masculine', declension: 1 },
  { word: 'αγρότης', english: 'farmer', gender: 'masculine', declension: 1 },
  { word: 'κύριος', english: 'mister/gentleman', gender: 'masculine', declension: 2 },
  { word: 'κυρία', english: 'miss/madam', gender: 'feminine', declension: 1 },
  { word: 'θείος', english: 'uncle', gender: 'masculine', declension: 2 },
  { word: 'θεία', english: 'aunt', gender: 'feminine', declension: 1 },
  { word: 'δημοκρατία', english: 'democracy', gender: 'feminine', declension: 1 },
  { word: 'πολιτική', english: 'politics', gender: 'feminine', declension: 1 },
  { word: 'κυβέρνηση', english: 'government', gender: 'feminine', declension: 1 },
  { word: 'νόμος', english: 'law', gender: 'masculine', declension: 2 },
  { word: 'ιστορία', english: 'history', gender: 'feminine', declension: 1 },
  { word: 'γεωγραφία', english: 'geography', gender: 'feminine', declension: 1 },
  { word: 'χημεία', english: 'chemistry', gender: 'feminine', declension: 1 },
  { word: 'φυσική', english: 'physics', gender: 'feminine', declension: 1 },
  { word: 'βιολογία', english: 'biology', gender: 'feminine', declension: 1 },
  { word: 'μαθηματικά', english: 'mathematics', gender: 'neuter', declension: 3 },
  { word: 'γλώσσα', english: 'language', gender: 'feminine', declension: 1 },
  { word: 'λέξη', english: 'word', gender: 'feminine', declension: 1 },
  { word: 'πρόταση', english: 'sentence', gender: 'feminine', declension: 1 },
  { word: 'κείμενο', english: 'text', gender: 'neuter', declension: 3 },
  { word: 'βιβλίο', english: 'book', gender: 'neuter', declension: 3 },
  { word: 'εφημερίδα', english: 'newspaper', gender: 'feminine', declension: 1 },
  { word: 'περιοδικό', english: 'magazine', gender: 'neuter', declension: 3 },
  { word: 'τηλεόραση', english: 'television', gender: 'feminine', declension: 1 },
  { word: 'ραδιόφωνο', english: 'radio', gender: 'neuter', declension: 3 },
  { word: 'κινηματογράφος', english: 'cinema/movie', gender: 'masculine', declension: 2 },
  { word: 'θέατρο', english: 'theater', gender: 'neuter', declension: 3 },
  { word: 'τραγούδι', english: 'song', gender: 'neuter', declension: 3 },
  { word: 'μουσική', english: 'music', gender: 'feminine', declension: 1 },
  { word: 'τέχνη', english: 'art', gender: 'feminine', declension: 1 },
  { word: 'ζωγραφία', english: 'painting', gender: 'feminine', declension: 1 },
  { word: 'σκοτάδι', english: 'darkness', gender: 'neuter', declension: 3 },
  { word: 'χρώμα', english: 'color', gender: 'neuter', declension: 3 },
  { word: 'σχήμα', english: 'shape', gender: 'neuter', declension: 3 },
  { word: 'μέγεθος', english: 'size', gender: 'neuter', declension: 3 },
  { word: 'βάρος', english: 'weight', gender: 'neuter', declension: 3 },
  { word: 'ύψος', english: 'height', gender: 'neuter', declension: 3 },
  { word: 'απόσταση', english: 'distance', gender: 'feminine', declension: 1 },
  { word: 'χρόνος', english: 'time', gender: 'masculine', declension: 2 },
  { word: 'ώρα', english: 'hour', gender: 'feminine', declension: 1 },
  { word: 'ημέρα', english: 'day', gender: 'feminine', declension: 1 },
  { word: 'νύχτα', english: 'night', gender: 'feminine', declension: 1 },
  { word: 'εβδομάδα', english: 'week', gender: 'feminine', declension: 1 },
  { word: 'μήνας', english: 'month', gender: 'masculine', declension: 1 },
  { word: 'έτος', english: 'year', gender: 'neuter', declension: 3 },
  { word: 'εποχή', english: 'season', gender: 'feminine', declension: 1 },
  { word: 'καιρός', english: 'weather', gender: 'masculine', declension: 2 },
  { word: 'βροχή', english: 'rain', gender: 'feminine', declension: 1 },
  { word: 'χιόνι', english: 'snow', gender: 'neuter', declension: 3 },
  { word: 'αέρας', english: 'wind', gender: 'masculine', declension: 1 },
  { word: 'ήλιος', english: 'sun', gender: 'masculine', declension: 2 },
  { word: 'σελήνη', english: 'moon', gender: 'feminine', declension: 1 },
  { word: 'αστέρι', english: 'star', gender: 'neuter', declension: 3 },
  { word: 'ουρανός', english: 'sky', gender: 'masculine', declension: 2 },
  { word: 'γη', english: 'earth', gender: 'feminine', declension: 1 },
  { word: 'βουνό', english: 'mountain', gender: 'neuter', declension: 3 },
  { word: 'λόφος', english: 'hill', gender: 'masculine', declension: 2 },
  { word: 'κοιλάδα', english: 'valley', gender: 'feminine', declension: 1 },
  { word: 'δάσος', english: 'forest', gender: 'neuter', declension: 3 },
  { word: 'λίμνη', english: 'lake', gender: 'feminine', declension: 1 },
  { word: 'ποτάμι', english: 'river', gender: 'neuter', declension: 3 },
  { word: 'θάλασσα', english: 'sea', gender: 'feminine', declension: 1 },
  { word: 'παραλία', english: 'beach', gender: 'feminine', declension: 1 },
  { word: 'χώρα', english: 'country', gender: 'feminine', declension: 1 },
  { word: 'πόλη', english: 'city', gender: 'feminine', declension: 1 },
  { word: 'χωριό', english: 'village', gender: 'neuter', declension: 3 },
  { word: 'δρόμος', english: 'street/road', gender: 'masculine', declension: 2 },
  { word: 'πλατεία', english: 'square', gender: 'feminine', declension: 1 },
  { word: 'σπίτι', english: 'house', gender: 'neuter', declension: 3 },
  { word: 'διαμέρισμα', english: 'apartment', gender: 'neuter', declension: 3 },
  { word: 'δωμάτιο', english: 'room', gender: 'neuter', declension: 3 },
  { word: 'κουζίνα', english: 'kitchen', gender: 'feminine', declension: 1 },
  { word: 'υπνοδωμάτιο', english: 'bedroom', gender: 'neuter', declension: 3 },
  { word: 'σαλόνι', english: 'living room', gender: 'neuter', declension: 3 },
  { word: 'μπάνιο', english: 'bathroom', gender: 'neuter', declension: 3 },
  { word: 'πόρτα', english: 'door', gender: 'feminine', declension: 1 },
  { word: 'παράθυρο', english: 'window', gender: 'neuter', declension: 3 },
  { word: 'τραπέζι', english: 'table', gender: 'neuter', declension: 3 },
  { word: 'καρέκλα', english: 'chair', gender: 'feminine', declension: 1 },
  { word: 'κρεβάτι', english: 'bed', gender: 'neuter', declension: 3 },
  { word: 'λάμπα', english: 'lamp', gender: 'feminine', declension: 1 },
  { word: 'τηλέφωνο', english: 'telephone', gender: 'neuter', declension: 3 },
];

module.exports = { articles, verbs, nouns };
